apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: pat-secret-sync
spec:
  vault:
    name: contoso_ops-kv-contoso_opssre-djo # name of key vault
    object:
      name: azdo-pat-admin # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: pat-secret-sync # kubernetes secret name
      dataKey: personalAccessToken # key to store object value in kubernetes secret