apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azdo-pat-sync
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
    - secretName: azdo-pat-secret
      type: Opaque
      data:
        - objectName: azdo-pat-secret
          key: personalAccessToken
  parameters:
    usePodIdentity: "true"
    keyvaultName: contoso_ops-kv-contoso_opssre-djo
    objects:  |
      array:
        - |
          objectName: azdo-pat-admin
          objectAlias: azdo-pat-secret
          objectType: secret
    tenantId: contoso_gitops.onmicrosoft.com